// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace web2.Migrations
{
  [DbContext(typeof(ApplicationContext))]
  [Migration("20221217215426_Inicial2")]
  partial class Inicial2
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "7.0.1")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      modelBuilder.Entity("web2.Models.Produto", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Codigo")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Nome")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<decimal>("Preco")
                      .HasColumnType("decimal(18,2)");

            b.HasKey("Id");

            b.ToTable("Produto");
          });
#pragma warning restore 612, 618
    }
  }
}
