// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace web2.Migrations
{
  [DbContext(typeof(ApplicationContext))]
  partial class AplicationContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "7.0.1")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      modelBuilder.Entity("web2.Models.Cadastro", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Bairro")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("CEP")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Complemento")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Endereco")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Municipio")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Nome")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Telefone")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("UF")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("Cadastro");
          });

      modelBuilder.Entity("web2.Models.ItemPedido", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<int>("PedidoId")
                      .HasColumnType("int");

            b.Property<decimal>("PrecoUnitario")
                      .HasColumnType("decimal(18,2)");

            b.Property<int>("ProdutoId")
                      .HasColumnType("int");

            b.Property<int>("Quantidade")
                      .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("PedidoId");

            b.HasIndex("ProdutoId");

            b.ToTable("ItemPedido");
          });

      modelBuilder.Entity("web2.Models.Pedido", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<int>("CadastroId")
                      .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("CadastroId")
                      .IsUnique();

            b.ToTable("Pedido");
          });

      modelBuilder.Entity("web2.Models.Produto", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Codigo")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Nome")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<decimal>("Preco")
                      .HasColumnType("decimal(18,2)");

            b.HasKey("Id");

            b.ToTable("Produto");
          });

      modelBuilder.Entity("web2.Models.ItemPedido", b =>
          {
            b.HasOne("web2.Models.Pedido", "Pedido")
                      .WithMany("Itens")
                      .HasForeignKey("PedidoId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("web2.Models.Produto", "Produto")
                      .WithMany()
                      .HasForeignKey("ProdutoId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Pedido");

            b.Navigation("Produto");
          });

      modelBuilder.Entity("web2.Models.Pedido", b =>
          {
            b.HasOne("web2.Models.Cadastro", "Cadastro")
                      .WithOne("Pedido")
                      .HasForeignKey("web2.Models.Pedido", "CadastroId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Cadastro");
          });

      modelBuilder.Entity("web2.Models.Cadastro", b =>
          {
            b.Navigation("Pedido");
          });

      modelBuilder.Entity("web2.Models.Pedido", b =>
          {
            b.Navigation("Itens");
          });
#pragma warning restore 612, 618
    }
  }
}
